name: tech_gate
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_pdfview: ^1.3.3
  path_provider: ^2.1.4
  pdfx: ^2.8.0
  device_info_plus: ^10.1.2
  google_maps_flutter: ^2.9.0
  location: ^7.0.1
  http: ^1.2.2
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  freezed: ^2.5.7
  flutter_spinkit: ^5.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/pdf/fletushka.pdf
    - .env
    - assets/placeholder.png
  
  